apiVersion: v1
data:
  password: N3R1R01YLTVZdG1aT005Zg==
kind: Secret
metadata:
  creationTimestamp: "2026-02-13T00:52:27Z"
  name: argocd-initial-admin-secret
  namespace: argocd
  resourceVersion: "6321"
  uid: 894449e4-22b9-4404-9246-1e194a812bfa
type: Opaque
